tense:
  - الماضي
  - المضارع المرفوع
  - المضارع المنصوب
  - المضارع المجزوم
  - الأمر
number:
  - المفرد
  - المثنّى
  - الجمع
person:
  - المتكلّم
  - المخاطب
  - المخاطبة
  - الغائب
  - الغائبة
verb:
  - s: دهب يذهب
    q: دَهَبَ-فتحة-متعدي
  - s: خَرَجَ يخرُجُ
    q: خَرَجَ-ضمة-متعدي
#  - رجعَ يرجِعُ
#  - فَهِمَ يَفْهَمُ
#  - سافر يُسافِرُ
#  - أحَبَّ يُحِبُّ
#  - درس يدرس
#  - سكن يسكن
#  - زَارَ يَزورُ
#  - قال يَقولُ
#  - كان يَكون
#  - نامَ يَنامُ
#  - خاف يَخاف
#  - عاشَ يَعيَش
